### ISSUE TITLE
You can have a constant for that path

### ISSUE THREAD

**Issue by AlexKap23** [lizzie992/Quiz-maker#3]
https://github.com/lizzie992/Quiz-maker/blob/bc16fb8250a203d090a1f09fcb5ee8e53449eb3d/Quiz%20maker/LogicalCode.cs#L19

Except the fact that it is hardcoded into your code, you are going to use the same one on the load option. So it would be much better if you could save it into a constant and use that constant instead.

**Comment by lizzie992** [comment]
I moved it into the constants but I get this error message which I cannot understand :(
![image](https://github.com/user-attachments/assets/a6c6fb65-296a-4a10-a9f7-4ce78d0bc746)
